import { UseDynamicContext } from '@dynamic-labs/sdk-react-core/src/lib/context/DynamicContext/useDynamicContext';

export default {
  isAuthenticated: true,
  network: 1,
  networkConfigurations: {
    evm: [
      {
        blockExplorerUrls: ['https://etherscan.io/'],
        chainId: 1,
        iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
        name: 'Ethereum Mainnet',
        nativeCurrency: {
          decimals: 18,
          name: 'Ether',
          symbol: 'ETH',
        },
        networkId: 1,
        rpcUrls: ['https://cloudflare-eth.com'],
        vanityName: 'Ethereum',
      },
      {
        blockExplorerUrls: ['https://bscscan.com'],
        chainId: 56,
        iconUrls: ['https://app.dynamic.xyz/assets/networks/bnb.svg'],
        name: 'BNB Smart Chain',
        nativeCurrency: {
          decimals: 18,
          name: 'BNB',
          symbol: 'BNB',
        },
        networkId: 56,
        rpcUrls: ['https://bsc-dataseed1.binance.org'],
      },
    ],
  },
  connectedWallets: [
    {
      address: '0x62eA30cFe51b1D1E7F0a8d3244Af46B3A91332f1',
      chain: 'eip155',
      connected: true,
      connector: {
        canConnectViaEmail: false,
        canConnectViaCustodialService: false,
        canConnectViaQrCode: false,
        canConnectViaSocial: false,
        isWalletConnect: false,
        isInitialized: true,
        constructorProps: {
          apiProviders: {},
          appLogoUrl:
            'https://venngage-wordpress.s3.amazonaws.com/uploads/2021/12/Plumbing-Logo-Template.png',
          appName: 'Your Crypto Dashboard',
          cosmosNetworks: [],
          evmNetworks: [
            {
              blockExplorerUrls: ['https://etherscan.io/'],
              chainId: 1,
              iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
              name: 'Ethereum Mainnet',
              nativeCurrency: {
                decimals: 18,
                name: 'Ether',
                symbol: 'ETH',
              },
              networkId: 1,
              rpcUrls: ['https://cloudflare-eth.com'],
              vanityName: 'Ethereum',
            },
            {
              blockExplorerUrls: ['https://bscscan.com'],
              chainId: 56,
              iconUrls: ['https://app.dynamic.xyz/assets/networks/bnb.svg'],
              name: 'BNB Smart Chain',
              nativeCurrency: {
                decimals: 18,
                name: 'BNB',
                symbol: 'BNB',
              },
              networkId: 56,
              rpcUrls: ['https://bsc-dataseed1.binance.org'],
            },
          ],
          isWalletConnectV2Enabled: true,
          projectId: '7569c63c696a4e8aeb3217c1b1332bd7',
          solNetworks: [],
          walletUiUtils: {},
        },
        evmNetworks: [
          {
            blockExplorerUrls: ['https://etherscan.io/'],
            chainId: 1,
            iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
            name: 'Ethereum Mainnet',
            nativeCurrency: {
              decimals: 18,
              name: 'Ether',
              symbol: 'ETH',
            },
            networkId: 1,
            rpcUrls: ['https://cloudflare-eth.com'],
            vanityName: 'Ethereum',
          },
          {
            blockExplorerUrls: ['https://bscscan.com'],
            chainId: 56,
            iconUrls: ['https://app.dynamic.xyz/assets/networks/bnb.svg'],
            name: 'BNB Smart Chain',
            nativeCurrency: {
              decimals: 18,
              name: 'BNB',
              symbol: 'BNB',
            },
            networkId: 56,
            rpcUrls: ['https://bsc-dataseed1.binance.org'],
          },
        ],
        supportedChains: ['ETH', 'EVM'],
        connectedChain: 'EVM',
        walletConnectorFallback: true,
        name: 'MetaMask',
      },
      id: 'fbaf6af1-3ebd-4b9a-9cb5-e2438476b895',
    },
    {
      address: '0x62eA30cFe51b1D1E7F0a8d3244Af46B3A91332f2',
      chain: 'eip155',
      connected: false,
      connector: {
        canConnectViaEmail: false,
        canConnectViaCustodialService: false,
        canConnectViaQrCode: false,
        canConnectViaSocial: false,
        isWalletConnect: false,
        isInitialized: true,
        constructorProps: {
          apiProviders: {},
          appLogoUrl:
            'https://venngage-wordpress.s3.amazonaws.com/uploads/2021/12/Plumbing-Logo-Template.png',
          appName: 'Your Crypto Dashboard',
          cosmosNetworks: [],
          evmNetworks: [
            {
              blockExplorerUrls: ['https://etherscan.io/'],
              chainId: 1,
              iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
              name: 'Ethereum Mainnet',
              nativeCurrency: {
                decimals: 18,
                name: 'Ether',
                symbol: 'ETH',
              },
              networkId: 1,
              rpcUrls: ['https://cloudflare-eth.com'],
              vanityName: 'Ethereum',
            },
            {
              blockExplorerUrls: ['https://bscscan.com'],
              chainId: 56,
              iconUrls: ['https://app.dynamic.xyz/assets/networks/bnb.svg'],
              name: 'BNB Smart Chain',
              nativeCurrency: {
                decimals: 18,
                name: 'BNB',
                symbol: 'BNB',
              },
              networkId: 56,
              rpcUrls: ['https://bsc-dataseed1.binance.org'],
            },
          ],
          isWalletConnectV2Enabled: true,
          projectId: '7569c63c696a4e8aeb3217c1b1332bd7',
          solNetworks: [],
          walletUiUtils: {},
        },
        evmNetworks: [
          {
            blockExplorerUrls: ['https://etherscan.io/'],
            chainId: 1,
            iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
            name: 'Ethereum Mainnet',
            nativeCurrency: {
              decimals: 18,
              name: 'Ether',
              symbol: 'ETH',
            },
            networkId: 1,
            rpcUrls: ['https://cloudflare-eth.com'],
            vanityName: 'Ethereum',
          },
          {
            blockExplorerUrls: ['https://bscscan.com'],
            chainId: 56,
            iconUrls: ['https://app.dynamic.xyz/assets/networks/bnb.svg'],
            name: 'BNB Smart Chain',
            nativeCurrency: {
              decimals: 18,
              name: 'BNB',
              symbol: 'BNB',
            },
            networkId: 56,
            rpcUrls: ['https://bsc-dataseed1.binance.org'],
          },
        ],
        supportedChains: ['ETH', 'EVM'],
        connectedChain: 'EVM',
        walletConnectorFallback: true,
        name: 'MetaMask',
      },
      id: '62958d87-a86c-4974-99e2-bfbd682c63ec',
    },
  ],
  setShowDynamicUserProfile: () => {},
} as unknown as UseDynamicContext;
