const SUPPORTED_BLOCKCHAINS = ['Ethereum', 'BNB Smart Chain']; // corresponding to Dynamic SDK vanityName ?? name of a blockchain

const QUERY_CACHE_TIMEOUT = 60 * 1000;

const DISPLAY_MAX_FRACTION_DIGITS = 9;
const DRAWER_WIDTH = 240;
const SNACKBAR_AUTOHIDE_TIME = 1000;

export {
  DISPLAY_MAX_FRACTION_DIGITS,
  DRAWER_WIDTH,
  QUERY_CACHE_TIMEOUT,
  SNACKBAR_AUTOHIDE_TIME,
  SUPPORTED_BLOCKCHAINS,
};
